### ISSUE TITLE
Run wc update command during deployment for WooCommerce Sites

### ISSUE THREAD

**Issue by grappler** [wearerequired/composer-deployer#18]
`wp wc update`

https://github.com/woocommerce/woocommerce/wiki/Upgrading-the-database-using-WP-CLI

**Comment by ocean90** [comment]
This can now be accomplished with the `post_rollout_commands` option added in https://github.com/wearerequired/composer-deployer/pull/31.

**Comment by grappler** [comment]
Example for this
```yml
.base: &base
  // …
  post_rollout_commands:
    - "{{bin/wp}} wc update"
 ```
